import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const read = (path) => readFile(new URL(path, root), 'utf8');
const licenses = await Promise.all(['LICENSE', 'licenses/Meridian.txt', 'licenses/Baseline.txt'].map(read));
const source = await read('src/claudian.css');

const header = `/* Claudian by Yishen Tu — generated by npm run build. Edit src/claudian.css instead.

Based on:
- Meridian 1.19.1 by mvahaste — https://github.com/mvahaste/meridian (MIT)
- Baseline 4.0.0 by svnaxis — https://github.com/svnaxis/obsidian-baseline (MIT)

${licenses.join('\n')}*/`;

await writeFile(new URL('theme.css', root), [header, source].join('\n\n'));
console.log('Built theme.css');
